/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.5
 * Generated at: 2020-09-04 09:37:13 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.user;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class login_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<script src=\"http://code.jquery.com/jquery-1.9.1.js\"></script>\r\n");
      out.write("\r\n");
      out.write("<form name=\"frm\">\r\n");
      out.write("<div style=\"border:1px solid black;margin-bottom:10px;padding:5px;\">\r\n");
      out.write("   <div style=margin-bottom:10px;>아이디　 <input type=\"text\" name=\"id\" size=8></div>\r\n");
      out.write("   <div style=margin-bottom:10px;>비밀번호 <input type=\"password\" name=\"password\" size=8></div>\r\n");
      out.write("   <div id=join style=\"background:#A5A0CE;\">\r\n");
      out.write("      <input type=\"submit\" value=\"로그인\"  style=\"margin-left:30px;\">\r\n");
      out.write("      <a href=\"/user/insert\" style=font-size:15px;text-decoration:none;color:white;>회원가입</a>\r\n");
      out.write("   </div>\r\n");
      out.write(" </div>\r\n");
      out.write("</form>\r\n");
      out.write("<script>\r\n");
      out.write("   $(frm).submit(function(e){\r\n");
      out.write("      e.preventDefault();\r\n");
      out.write("      \r\n");
      out.write("      var id=$(frm.id).val();\r\n");
      out.write("      var password=$(frm.password).val();\r\n");
      out.write("      \r\n");
      out.write("      if(id==\"\"|| password==\"\"){\r\n");
      out.write("         alert(\"아이디 또는 비밀번호를 입력하세요\");\r\n");
      out.write("      }else{\r\n");
      out.write("         $.ajax({\r\n");
      out.write("            type:\"post\",\r\n");
      out.write("            url:\"/user/login\",\r\n");
      out.write("            data:{\"id\":id,\"password\":password},\r\n");
      out.write("            dataType:\"json\",\r\n");
      out.write("            success:function(data){\r\n");
      out.write("               if(data.id==null){\r\n");
      out.write("                  alert(\"아이디 또는 비밀번호가 일치하지 않습니다.\");\r\n");
      out.write("               }else{\r\n");
      out.write("                  location.href=\"/index.jsp\";\r\n");
      out.write("               }\r\n");
      out.write("            }\r\n");
      out.write("         });\r\n");
      out.write("      }\r\n");
      out.write("   });\r\n");
      out.write("</script>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
