/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.5
 * Generated at: 2020-06-19 04:52:24 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class top_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write(" \r\n");
      out.write("    <div id=\"divTop\" style=width:100%;height:37px;background:#2569C9>\r\n");
      out.write("      <div style=width:180px;height:30px;text-align:center;background:#6F9CDB;float:left;margin-left:450px;padding-top:7px;><a style=color:white;text-decoration:none href=\"../index.jsp\">투웨니포세븐</a></div>\r\n");
      out.write("      <div style=width:510px;float:right;padding-right:430px;>\r\n");
      out.write("         <table style=background:none;font-color:white;font-size:12px;border-collapse:collapse>\r\n");
      out.write("            <tr style=height:35px;>     \r\n");
      out.write("            \t<td style=padding-left:15px;padding-right:15px;width:80px><a style=color:white;text-decoration:none href=\"../user/company_login.jsp\">관리자로그인</a></td>          \r\n");
      out.write("               <td style=padding-left:15px;padding-right:15px;width:80px><a style=color:white;text-decoration:none href=\"../user/cvs_login.jsp\">점주로그인</a></td>\r\n");
      out.write("               <td style=padding-left:5px;padding-right:5px;width:80px><a style=color:white;text-decoration:none href=\"../user/insert.jsp\">회원가입</a></td>\r\n");
      out.write("               <td style=padding-left:5px;padding-right:5px;width:80px><a style=color:white;text-decoration:none href=\"\">고객센터</a></td>\r\n");
      out.write("               <td style=padding-left:5px;padding-right:5px;width:80px><a style=color:white;text-decoration:none href=\"../about_company.jsp\">회사소개</a></td>             \r\n");
      out.write("            <tr>\r\n");
      out.write("         </table>\r\n");
      out.write("      </div>\r\n");
      out.write("    </div>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
